
#server:
#  port: 8082
#spring:
#  kafka:
#    bootstrap-servers: localhost:9092

server:
  port: 8082

spring:
  application:
    name: inventory-service

  datasource:
    url: jdbc:h2:mem:inventorydb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true   #to Wait until Hibernate creates tables, THEN run data.sql

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: inventory-group        # REQUIRED
      auto-offset-reset: earliest      # Start from beginning if no offset
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    #  key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
   #   value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
         spring.json.trusted.packages: com.retail.event
         spring.json.value.default.type: com.retail.event.OrderCreatedEvent
      #   spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
     #    spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer

    listener:
      ack-mode: RECORD
    producer:     ##producer required to publish msg to dlt topic in case of failure (DLQ)
      bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
 
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true