
#server:
#  port: 8081
#spring:
#  application:
#    name: product-service
#  datasource:
#    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
#    username: retail
#    password: retail
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
server:
  port: 8081   # Product service port

spring:
  application:
    name: product-service

  datasource:
    url: jdbc:h2:mem:productdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update   # Auto-create tables
    show-sql: true
    defer-datasource-initialization: true   #to Wait until Hibernate creates tables, THEN run data.sql

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
         web-allow-others: true